### PR TITLE
* Implement point # 2 #728

### PR DESCRIPTION
**Pull request by Wagnerp**
- `MdiChildrenMinimizedAnchorBottom`

image

### CODE REVIEW

**Comment by Smurf-IV** [comment]
The "Idea" of these changes is to bring the functionality "Down" from .Net 6 / 7 into the earlier versions, so that a Single code base will work for multi-target builds.

**Comment by Wagnerp** [comment]
> The "Idea" of these changes is to bring the functionality "Down" from .Net 6 / 7 into the earlier versions, so that a Single code base will work for multi-target builds.

We need to find out what the `MdiChildrenMinimizedAnchorBottom` option exactly does & has anyone modified it to work on older frameworks.

**Comment by Smurf-IV** [comment]
@Wagnerp Is this still valid ?

**Comment by Wagnerp** [comment]
> @Wagnerp Is this still valid ?

No, closing

**Pull request closed without merging**
