### PR TITLE
- Remove the Auto Versioning on Each build

### PR DESCRIPTION
**Pull request by Smurf-IV**
- Update Project and Readme text description

### CODE REVIEW

**Review by Wagnerp — COMMENTED** [review]
Merged changes :)

**Comment by Smurf-IV** [comment]
@Wagnerp Should this go into "Canary" as well ?

**Comment by Wagnerp** [comment]
@Smurf-IV Yes, it will be merged in build 2106. I really use the `alpha` branch as active development.

**Comment by Smurf-IV** [comment]
So New development and fixes into alpha, then you merge them into master afterwards ?
Can / Should this "WorkFlow" be documented please ?

**Comment by Wagnerp** [comment]
Sure, I'll create a new document in the `Documents` folder.

**Comment by Wagnerp** [comment]
Added `Development-Workflow.md` feel free to edit as required.

**Pull request merged**
