### PR TITLE
* #336 Fix

### LINKED ISSUE #336: [Bug]: "Office 2010 And 365 Minimise Icons Change Size" on hover
**Describe the bug**
When hovering over the minimise button, it is of a different size that it's normal state, and also the minimise icons moves.

Only applies to 201 and 365 themes 

Tested with 2109 Canary - May be applicable to earlier versions

Office2010And365MinimiseIconsChangeSize

### PR DESCRIPTION
**Pull request by Wagnerp**
- Fixes #336 

image

### CODE REVIEW

**Comment by Smurf-IV** [comment]
Why has the warnings jumped to 679.. Last I saw they were 518 ??

**Comment by Wagnerp** [comment]
> Why has the warnings jumped to 679.. Last I saw they were 518 ??

Might be because I've introduced the minimise hover for O2k10 & 365 which are null values at the moment.

**Comment by Smurf-IV** [comment]
Is there a nightly build yet (Manual or otherwise) ?

**Comment by Wagnerp** [comment]
> Is there a nightly build yet (Manual or otherwise) ?

Going to push todays one now

**Comment by Smurf-IV** [comment]
Do you think that the Canary 6.0.2108.1 Should be converted to the last version of V5 - just to allow those who have been looking for updates have something to use ?

**Comment by Smurf-IV** [comment]
image

**Comment by Smurf-IV** [comment]
Cannot install Ribbon or Navigator due to incorrect dependent versions:
image

I do not think that the MM and SS are really necessary in the name version or listing.

**Comment by Wagnerp** [comment]
The time is causing a issue, may shorten it to `yyyyMMdd`

**Comment by Wagnerp** [comment]
> Do you think that the Canary 6.0.2108.1 Should be converted to the last version of V5 - just to allow those who have been looking for updates have something to use ?

Do you mean include all TFMs?

**Comment by Smurf-IV** [comment]
> Do you mean include all TFMs?

That's the standard listing in visual studio when it "Interogates" the nuget data package

**Comment by Wagnerp** [comment]
Ahh... I see 6.0.2108.1 -> 5.550.2108?

**Comment by Smurf-IV** [comment]
> Ahh... I see 6.0.2108.1 -> 5.550.2108?

Yes, Remove netcore -> net 6 and leave it as standard / original NetFrameworks.

**Comment by Wagnerp** [comment]
I'll do it now

**Pull request merged**
