### PR TITLE
* Resolved #1837 - V85

### LINKED ISSUE #1837: [Bug]: `KryptonMessageBoxDefaultButton.Button2` doesn't work
**Describe the bug**
`KryptonMessageBoxDefaultButton.Button2` or `KryptonMessageBoxDefaultButton.Button3` doesn't work and button1 always gets the focus.

**To Reproduce**
```cs
KryptonMessageBox.Show("question?", "title", KryptonMessageBoxButtons.YesNo, 
                       KryptonMessageBoxIcon.Warning, KryptonMessageBoxDefaultButton.Button2);
```

**Expected behavior**
Button2 (the No button in this case) should have the focus. However, button1 (Yes) gets the focus instead.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Framework/.NET Version: .NET 8.0
 - Toolkit Version: 85.24.10.288

### PR DESCRIPTION
**Pull request by PWagner1**
* Resolved #1837 - V85

image

### CODE REVIEW

**Comment by giduac** [comment]
DONT MERGE FOR NOW.
Needs a bit more work....

**Comment by PWagner1** [comment]
@giduac & @Smurf-IV 

Fix verified as working

**Comment by Smurf-IV** [comment]
@PWagner1 Am I missing a V90 review somewhere ?

**Comment by PWagner1** [comment]
> @PWagner1 Am I missing a V90 review somewhere ?

@Smurf-IV No, it'll be fixed post V90 in a patch to avoid 'commits ahead/behind' chaos

**Pull request merged**
