### PR TITLE
* Remove .NET 6

### PR DESCRIPTION
**Pull request by PWagner1**
* Removed . NET 6

{18761F1A-1AA9-437C-99E8-9ADB808F258A}

(Warnings relate to #1771)

### CODE REVIEW

**Comment by giduac** [comment]
@PWagner1 
Personally favoring setting WFO1000 to `silent` since we don't need to keep track of the warning count when running build all the time. In short it's a bit unhandy...

We need open a ticket anyway where DN9 breaking changes will be evaluated and WFO1000 is part of that.

**Comment by PWagner1** [comment]
> @PWagner1 Personally favoring setting WFO1000 to `silent` since we don't need to keep track of the warning count when running builds all the time. In short, it's a bit unhandy...
> 
> We need open a ticket anyway where DN9 breaking changes will be evaluated and WFO1000 is part of that.

@giduac 

Now silent, but needs resolving

{FD687A46-3D99-4782-B4FB-74F48785382C}

cc. @Smurf-IV

**Comment by giduac** [comment]
> > @PWagner1 Personally favoring setting WFO1000 to `silent` since we don't need to keep track of the warning count when running builds all the time. In short, it's a bit unhandy...
> > We need open a ticket anyway where DN9 breaking changes will be evaluated and WFO1000 is part of that.
> 
> @giduac
> 
> Now silent, but needs resolving
> 
> {FD687A46-3D99-4782-B4FB-74F48785382C}
> 
> cc. @Smurf-IV

Will be evaluated in https://github.com/Krypton-Suite/Standard-Toolkit/issues/1777

**Comment by Smurf-IV** [comment]
@PWagner1 conflicts.

**Comment by PWagner1** [comment]
> @PWagner1 conflicts.

@Smurf-IV 

Resolved

**Review by giduac — APPROVED** [review]

**Pull request merged**
