### PR TITLE
* A better build system

### PR DESCRIPTION
**Pull request by Wagnerp**
* See changelog

### CODE REVIEW

**Comment by Wagnerp** [comment]
image

image

**Comment by Wagnerp** [comment]
`run.cmd` has been tested & working as intended

**Comment by Wagnerp** [comment]
Overall, the changes has cut a lot of unnecessary configuration out.

**Comment by Wagnerp** [comment]
@Smurf-IV I'm going to have to take some time out 'delisting' packages, as 6.2112.x > 6.22.1.x

**Comment by Wagnerp** [comment]
@Smurf-IV This is now ready

**Comment by Smurf-IV** [comment]
These still need sorting:
image

**Comment by Wagnerp** [comment]
> These still need sorting: image

Done!

**Comment by Smurf-IV** [comment]
?
image

**Comment by Wagnerp** [comment]
> ? image

@Smurf-IV Delisting issue, forgot to delist the old versions. Will look into it.

**Comment by Wagnerp** [comment]
@Smurf-IV That's odd, seems to be ok

image

image

**Comment by Smurf-IV** [comment]
perhaps it's a weirdness in VS2019, and the project already having the "Old" references....

**Pull request merged**
