### PR TITLE
Catchup 27/04/2024 #3

### PR DESCRIPTION
**Pull request by Wagnerp**

### CODE REVIEW

**Comment by giduac** [comment]
@Wagnerp 

Since this merge Alpha won't build anymore and produces several errors at the end of the build.
Can you try to build Alpha as see how that goes on your side...?

One of the errors I get.

```cmd
"D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Scripts\nightly.proj" (Build target) (1) ->
"D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Docking\Krypton.Docking 2022.csproj" (default target) (2:47) ->
"D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Docking\Krypton.Docking 2022.csproj" (Build target) (2:53) ->
"D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\Krypton.Navigator 2022.csproj" (default target) (3:86) ->
"D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Krypton.Toolkit 2022.csproj" (default target) (4:105) ->
  C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3386,5): error MSB3553: Resource file "obj\Nightly\net481\Krypton.Toolkit.Controls_Visuals.Notificati
on_Toast.User_Input.Left_to_Right.ProgressBar.VisualToastNotificationComboBoxUserInputWithProgressBarForm.resources" has an invalid name. The item metadata "%(FullPath)" cannot be applied to the path "obj\Nightly\net481
\Krypton.Toolkit.Controls_Visuals.Notification_Toast.User_Input.Left_to_Right.ProgressBar.VisualToastNotificationComboBoxUserInputWithProgressBarForm.resources". Path: obj\Nightly\net481\Krypton.Toolkit.Controls_Visuals
.Notification_Toast.User_Input.Left_to_Right.ProgressBar.VisualToastNotificationComboBoxUserInputWithProgressBarForm.resources exceeds the OS max path limit. The fully qualified file name must be less than 260 character
s. [D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Krypton.Toolkit 2022.csproj::TargetFramework=net481]
```

**Comment by Wagnerp** [comment]
> @Wagnerp
> 
> Since this merge Alpha won't build anymore and produces several errors at the end of the build. Can you try to build Alpha as see how that goes on your side...?
> 
> One of the errors I get.
> 
> ```batchfile
> "D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Scripts\nightly.proj" (Build target) (1) ->
> "D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Docking\Krypton.Docking 2022.csproj" (default target) (2:47) ->
> "D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Docking\Krypton.Docking 2022.csproj" (Build target) (2:53) ->
> "D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\Krypton.Navigator 2022.csproj" (default target) (3:86) ->
> "D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Krypton.Toolkit 2022.csproj" (default target) (4:105) ->
>   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3386,5): error MSB3553: Resource file "obj\Nightly\net481\Krypton.Toolkit.Controls_Visuals.Notificati
> on_Toast.User_Input.Left_to_Right.ProgressBar.VisualToastNotificationComboBoxUserInputWithProgressBarForm.resources" has an invalid name. The item metadata "%(FullPath)" cannot be applied to the path "obj\Nightly\net481
> \Krypton.Toolkit.Controls_Visuals.Notification_Toast.User_Input.Left_to_Right.ProgressBar.VisualToastNotificationComboBoxUserInputWithProgressBarForm.resources". Path: obj\Nightly\net481\Krypton.Toolkit.Controls_Visuals
> .Notification_Toast.User_Input.Left_to_Right.ProgressBar.VisualToastNotificationComboBoxUserInputWithProgressBarForm.resources exceeds the OS max path limit. The fully qualified file name must be less than 260 character
> s. [D:\Data\Source\Repos\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Krypton.Toolkit 2022.csproj::TargetFramework=net481]
> ```

@giduac 

Can confirm that it does build?

image

**Comment by Smurf-IV** [comment]
@giduac 
Have you tried the Registry change?
https://stackoverflow.com/questions/73834326/attempt-to-build-project-results-in-path-error-path-length-is-too-long-will-mo
Never done this myself, so perhaps it's something to do with the Formatting of the drive ??

**Comment by giduac** [comment]
@Smurf-IV 
Yeah I did that yesterday. Never changed it but knew about the possibility.
https://thegeekpage.com/make-windows-11-accept-file-paths-over-260-characters/

Can be done while running. 
I did it the gpedit way (run as administrator) which took effect immediately without logoff or a reboot.

**Pull request merged**
