### PR TITLE
- Implement reasons to allow Maximum size to be respected

### LINKED ISSUE #459: [Bug]: KryptonForm.MaximumSize doesn't have any effect
**Describe the bug**
Setting the `KryptonForm.MaximumSize` property does not restrict resizing the form beyond the selected size.

**To Reproduce**
1. Set the `MaximumSize` property of a form to any size other than `Size.Empty`.
2. Run the program and try to resize the form beyond the selected size.
3. It will resize as far as the screen allows.

**Expected behavior**
The form shouldn't resize beyond the `MaximumSize` property's value.

**Desktop:**
 - OS: Windows 10 64-bit
 - Version 21H1

**Additional context**
I've narrowed down the issue to the `OnWM_GETMINMAXINFO` method in `VisualForm`. That method gets called in `WndProc` and although I'm not entirely sure about the purpose of it or if it's really needed, there's a [comment](https://github.com/Krypton-Suite/Standard-Toolkit/blob/1c2e44a7f607ff27043af5a50921a628f13ffba7/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Visuals/VisualForm.cs#L1035) there about allowing the application to process its own min/max requirements by setting the `processed` bool variable to false. However, at the end of `WndProc` when it's time to call `base.WndProc`, there's a [check](https://github.com/Krypton-Suite/Standard-Toolkit/blob/1c2e44a7f607ff27043af5a50921a628f13ffba7/Source/Krypton%20Components/Krypton.Toolkit/Controls%20Visuals/VisualForm.cs#L1138) for `m.Msg != PI.WM_.GETMINMAXINFO` (which contradicts with the comment referred to above).

### PR DESCRIPTION
**Pull request by Smurf-IV**
Fix #459

### CODE REVIEW

**Review by Wagnerp — APPROVED** [review]

**Comment by Smurf-IV** [comment]
@Wagnerp `Build-2019.cmd` produces errors:

image

**Comment by Wagnerp** [comment]
> @Wagnerp `Build-2019.cmd` produces errors:
> 
> image

@Smurf-IV Might be an issue with `Build Tools 2019`, it's ok with 2022

**Comment by Smurf-IV** [comment]
> @Smurf-IV Might be an issue with `Build Tools 2019`, it's ok with 2022

Yes:
image

**Comment by Smurf-IV** [comment]
But then all the analysers etc. have been disabled, so no idea what code style things need to be fixed !

**Comment by Wagnerp** [comment]
> > @Smurf-IV Might be an issue with `Build Tools 2019`, it's ok with 2022
> 
> Yes: image

```xml
 <Choose>
        <When Condition="'$(Configuration)' == 'Release'">
            <PropertyGroup>
                <LangVersion>latest</LangVersion>
                <AnalysisLevel>latest</AnalysisLevel>
            </PropertyGroup>
        </When>
        <Otherwise>
            <PropertyGroup>
                <LangVersion>preview</LangVersion>
                <AnalysLevel>preview</AnalysLevel>
                <IncludeSymbols>true</IncludeSymbols>
            </PropertyGroup>
        </Otherwise>
    </Choose>
```

**Pull request merged**
