### PR TITLE
* Groundwork for #1343

### PR DESCRIPTION
**Pull request by Wagnerp**
* Groundwork for #1343
   - Need to remove hard coded value

image

### CODE REVIEW

**Comment by Wagnerp** [comment]
@Smurf-IV Would you mind checking this please, as I don't know where the `null` palette is coming from? Thanks :)

**Comment by Smurf-IV** [comment]
> @Smurf-IV Would you mind checking this please, as I don't know where the `null` palette is coming from? Thanks :)

I'll need more information as to what to look for in what Test form please ?

**Comment by Wagnerp** [comment]
> > @Smurf-IV Would you mind checking this please, as I don't know where the `null` palette is coming from? Thanks :)
> 
> I'll need more information as to what to look for in what Test form please ?

@Smurf-IV If you choose the `Microsoft 365 - Black (Dark Mode)` (as that's the only theme so far I've changed colours for yet), then choose 'Ribbon', it should demonstrate the crash.

**Comment by Smurf-IV** [comment]
OK looking at this now.....

> @Smurf-IV If you choose the `Microsoft 365 - Black (Dark Mode)` (as that's the only theme so far I've changed colours for yet), then choose 'Ribbon', it should demonstrate the crash.

It also crashes just by using the default - 365 blue


> I think it's something in `KryptonRibbon.cs`, namely lines 86, 2573 & 2597. Also, changes were made to `RibbonAppButton.cs`.

I agree, What was `_ribbonGeneralInherit` for ?

**Comment by Smurf-IV** [comment]
Sorted, Take the latest code..
Now sort out the colouring of the "File" tab for all of the other themes

**Comment by Wagnerp** [comment]
> Sorted, Take the latest code.. Now sort out the colouring of the "File" tab for all of the other themes

Thanks, will sort out the colours.

**Comment by Wagnerp** [comment]
@Smurf-IV I will close & reopen a new branch based on the latest `alpha` to avoid merge madness.

**Pull request closed without merging**
