### PR TITLE
Alpha ARM64 (Backburner)

### PR DESCRIPTION
**Pull request by Wagnerp**
* ARM/ARM64 support - may need looking at (only works for .NET 6!)

### CODE REVIEW

**Comment by Smurf-IV** [comment]
Will this make a mess of installers that redistribute these dll's ?
i.e. they will ned to have an x64 and an x86 directory.

Isn't `AnyCPU` supposed to solve the **need** for these explicit identifiers

**Comment by Wagnerp** [comment]
> Will this make a mess of installers that redistribute these dll's ?
> i.e. they will ned to have an x64 and an x86 directory.
> 
> Isn't `AnyCPU` supposed to solve the **need** for these explicit identifiers

As I understand it, the `RuntimeIdentifiers` is new to .NET 5/6. I don't know if this is going to supersede `AnyCPU` eventually. Here are the doc notes: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

**Comment by Wagnerp** [comment]
May wait for the snapdragon dev kit to test, as I don't think Win 10 can run on a Raspberry PI

**Comment by Smurf-IV** [comment]
If the RID stuff is to be followed, then that also means a lot of dll naming needs to be done.
As this "Suite" is just for windows, I would ignore it for now.

**Comment by Smurf-IV** [comment]
https://www.zdnet.com/article/op-ed-windows-isnt-ready-for-arm-developers/

**Comment by Wagnerp** [comment]
Closing due to the state of ARM64 support in Windows 11 today. Maybe something to revisit in the future.

**Pull request closed without merging**
