### PR TITLE
* Icons

### PR DESCRIPTION
**Pull request by Wagnerp**
Colour dialog

image

image

image

### CODE REVIEW

**Comment by Wagnerp** [comment]
Print dialog...

image

image

image

**Comment by Smurf-IV** [comment]
> 
> 
> > > > Font Dialog ?
> > > 
> > > 
> > > Going to create a icon from scratch
> > 
> > 
> > ??
> 
> None of the icons I've looked at were that great. Possibly go for an 'Aa' design

??

**Comment by Wagnerp** [comment]
> > > > > Font Dialog ?
> > > > 
> > > > 
> > > > Going to create a icon from scratch
> > > 
> > > 
> > > ??
> > 
> > 
> > None of the icons I've looked at were that great. Possibly go for an 'Aa' design
> 
> ??

@Smurf-IV Hopefully will be working on this soon, just want to get the extended KMessagebox to a workable state before moving on

**Comment by Smurf-IV** [comment]
> 
> 
> @Smurf-IV Just an idea...
> 
> Font

Will that work when it is compressed down to 16*16 and in a Frame title ?

**Comment by Wagnerp** [comment]
Could use the same design as the main toolkit icon, but in a different colour?

image

**Pull request merged**
