### PR TITLE
- Make sure keyTipControl does not have `Shadow State` turned on.

### PR DESCRIPTION
**Pull request by Smurf-IV**
- tidyup a few conditions as I was exploring
#630

Note: when running the `run.cmd` not from within the directory results in errors:
image

### CODE REVIEW

**Comment by Smurf-IV** [comment]
image

**Comment by Wagnerp** [comment]
> * tidyup a few conditions as I was exploring
>   [[Bug]: Ribbon accelerator overlay has shadowing #630](https://github.com/Krypton-Suite/Standard-Toolkit/issues/630)
> 
> Note: when running the `run.cmd` not from within the directory results in errors: image

@Smurf-IV Was that when using the 'Debug' option?

**Review by Wagnerp — APPROVED** [review]

**Comment by Smurf-IV** [comment]
> @Smurf-IV Was that when using the 'Debug' option?

No, 2 then 2

**Comment by Wagnerp** [comment]
> > @Smurf-IV Was that when using the 'Debug' option?
> 
> No, 2 then 2

@Smurf-IV Would you mind testing the version on the `themes` branch, as I've made some edits to the script today?

**Pull request merged**
