### PR TITLE
Fixed adding new Page to vacated Cell

### PR DESCRIPTION
**Pull request by stigzler**
Forgive me. I'm a hobby coder and this is my first pull request so please forgive any etiquette faux pas!

Original Issue: [Git Issue](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1383)

Have tested - seems to work well, but not aware of the wider architecture, so may need some review. Also, my code felt a bit smelly. My original (more readable?) code below, but held some repetition:

```cs
if (cell == null)
{
    // ...create a new cell and place at the end of the root collection
    cell = new KryptonWorkspaceCell();
    SpaceControl!.Root.Children!.Add(cell);
}
else if (cell.Pages.Count() == 0)
{
    // first remove the empty cell
    SpaceControl!.Root.Children!.Remove(cell);
    // now create a new cell and place at the end of the root collection
    cell = new KryptonWorkspaceCell();
    SpaceControl!.Root.Children!.Add(cell);
}
```
Likely a matter of taste?

Hope helps!

### CODE REVIEW

**Comment by Smurf-IV** [comment]
@stigzler Please merge target into `alpha`
Then run the `run.cmd` Option 2, then 1 and add the last few lines of the build output (So that we can see it compiles clean and the warnings do not go "up")
Please have a look at the other completed PR 's as an aexample

**Comment by Smurf-IV** [comment]
Also Build against "Alpha" version of the examples and run through them to ensure that they still work as expected

**Comment by stigzler** [comment]
Thanks Smurf. Sorry, as I say, I'm a hobby coder, so this isn't my day job. Have changed the branch to Alpha, but how do I do the run.cmd stuff? Where do I do that or what terms do I search on to find out how to do it?

**Comment by stigzler** [comment]
Sorry chaps. Do I still need to do anything? I see Wagnerp has submitted it for review or something by yourself, Smurf? Again, forgive me - I don't normally use git to this level..

**Comment by Wagnerp** [comment]
> Sorry chaps. Do I still need to do anything? I see Wagnerp has submitted it for review or something by yourself, Smurf? Again, forgive me - I don't normally use git to this level..

Hi @stigzler 

This PR can be closed, as it was merged yesterday in PR #1385

**Comment by stigzler** [comment]
Thanks. My first ever pull request on a public project! (git-wise - had no idea what I was doing!)

**Comment by Wagnerp** [comment]
> Thanks. My first ever pull request on a public project! (git-wise - had no idea what I was doing!)

Hi @stigzler No problem, should you wish to create any more pull requests in the future, we do have a step-by-step guide on how to do it [here](https://github.com/Krypton-Suite/Documentation/blob/main/Documents/Development/How-to-Create-a-Pull-Request.md).

**Comment by stigzler** [comment]
Perfect. Thanks.

**Pull request closed without merging**
