### PR TITLE
- Make the code changes ready for the Help Icon in the ButtonSpec

### PR DESCRIPTION
**Pull request by Smurf-IV**
Part of #219

### CODE REVIEW

**Comment by Wagnerp** [comment]
@Smurf-IV Is this ready to go?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Is this ready to go?

@Wagnerp 
Currently it will break the build due to the missing resource files I mentioned.
I put it here so that you can grab - Add files / update resources / get it working, and then perform the sort out of the other resources in the other task that you are doing.

**Comment by Wagnerp** [comment]
> > @Smurf-IV Is this ready to go?
> 
> @Wagnerp
> Currently it will break the build due to the missing resource files I mentioned.
> I put it here so that you can grab - Add files / update resources / get it working, and then perform the sort out of the other resources in the other task that you are doing.

I'll start editing the resources tomorrow

**Comment by Wagnerp** [comment]
@Smurf-IV Hoping to complete over the weekend, checkboxes may need to wait for a tad longer

**Comment by Wagnerp** [comment]
@Smurf-IV Passing the baton over to you to review :)

The help icon images have now been implemented 

image

**Review by Wagnerp — APPROVED** [review]

**Comment by Wagnerp** [comment]
@Smurf-IV Is this ready to go?

**Comment by Smurf-IV** [comment]
> 
> 
> @Smurf-IV Is this ready to go?

Is there going to be an equivalent update to the demo's to show the "New things" you've done for the UAC etc as well ?

**Comment by Wagnerp** [comment]
> > @Smurf-IV Is this ready to go?
> 
> Is there going to be an equivalent update to the demo's to show the "New things" you've done for the UAC etc as well ?

Yes, will add to the demos tomorrow :)

**Pull request merged**
