### PR TITLE
* Added `More Details` & `Less Details` strings

### PR DESCRIPTION
**Pull request by Wagnerp**
* Added More Details & Less Details strings

image

### CODE REVIEW

**Comment by Wagnerp** [comment]
Updated log :)

image

**Comment by Smurf-IV** [comment]
image

**Comment by Wagnerp** [comment]
> image

So remove `DEFAULT_MORE_DETAILS` & `DEFAULT_LESS_DETAILS`? 

BTW it's weird that I can't see your comments? (using Edge & Edge Canary)

**Comment by Wagnerp** [comment]
> image

Commented them out for the time being

image

**Pull request merged**
