### PR TITLE
- Make the blur work in the supported OS's

### PR DESCRIPTION
**Pull request by Smurf-IV**
- Ensure messagebox code works
- Grab image of source before loss of focus to ensure correct colouring
- Remove code that is no longer applicable
Resolves:
  - #70
  - #69
  - #68

### CODE REVIEW

**Comment by Smurf-IV** [comment]
@Wagnerp Cannot load solution into VS2019 any more??
image
And it does not build from the command line.

**Comment by Wagnerp** [comment]
> @Wagnerp Cannot load solution into VS2019 any more?? image And it does not build from the command line.
> 
> When re-adding in VS2019 It displays this: image

@Smurf-IV I'll take a look at it later :)

**Comment by Wagnerp** [comment]
@Smurf-IV Just checked on VS2019, doesn't seem to have any issues?

image

**Comment by Smurf-IV** [comment]
Just tried with the current alpha, and I get the same.
image

**Comment by Wagnerp** [comment]
Now that's odd, I'm on the current alpha, and I get this:

image

**Pull request merged**
