### PR TITLE
Alpha resource sorting

### PR DESCRIPTION
**Pull request by Wagnerp**
* #256

### CODE REVIEW

**Comment by Smurf-IV** [comment]
Still draft, Is it ready ?

**Comment by Wagnerp** [comment]
> Still draft, Is it ready ?

Still draft, there's lots of duplicates to go through

**Comment by Wagnerp** [comment]
* Pt. 1
* Some ToDos may need converting into issues TBRs

**Comment by Wagnerp** [comment]
Forgot this

image

**Pull request merged**
