### PR TITLE
Simplified some code for a test commit

### PR DESCRIPTION
**Pull request by NicodemusU**
Simplified some code so I can test creating a pull request from a fork into the alpha branch

### CODE REVIEW

**Review by Wagnerp — APPROVED** [review]

**Comment by Smurf-IV** [comment]
@NicodemusU Welcome

**Comment by Wagnerp** [comment]
Hi @NicodemusU 

Welcome to the project :)

**Comment by giduac** [comment]
Welcome @NicodemusU 

@Smurf-IV & @Wagnerp 
I can be mistaken but don't we always use curly braces?

**Comment by Wagnerp** [comment]
> Welcome @NicodemusU
> 
> @Smurf-IV & @Wagnerp I can be mistaken but don't we always use curly braces?

Hi @giduac 

I've now fixed it in my branch, plus I have slightly improved it using ReSharper

```cs
if (!Values.ShowSplitOption || ContextMenuStrip is not { Visible: true })
            {
                base.OnMouseUp(e);
            }
```

**Comment by giduac** [comment]
> > Welcome @NicodemusU
> > @Smurf-IV & @Wagnerp I can be mistaken but don't we always use curly braces?
> 
> Hi @giduac
> 
> I've now fixed it in my branch, plus I have slightly improved it using ReSharper
> 
> ```cs
> if (!Values.ShowSplitOption || ContextMenuStrip is not { Visible: true })
>             {
>                 base.OnMouseUp(e);
>             }
> ```
@Wagnerp & @NicodemusU 

Then it can even be a little shorter:
```cs
if (!Values.ShowSplitOption || ContextMenuStrip is { Visible: false })
```

**Pull request merged**
