### PR TITLE
Alpha fix#603

### PR DESCRIPTION
**Pull request by Wagnerp**
* Reinstate fixes for #603 

image

### CODE REVIEW

**Comment by Wagnerp** [comment]
@Smurf-IV This can be merged

image

**Comment by Smurf-IV** [comment]
> @Smurf-IV This can be merged


I do not see my comments resolved tho ?

**Comment by Wagnerp** [comment]
> > @Smurf-IV This can be merged
> 
> I do not see my comments resolved tho ?

@Smurf-IV Could you link to the comments please, as I don't see them? :)

**Comment by Smurf-IV** [comment]
Just scroll up:
image

with the PR open: https://github.com/Krypton-Suite/Standard-Toolkit/pull/773

**Comment by Wagnerp** [comment]
> Just scroll up: image
> 
> with the PR open: #773

Ok, fixed these issues. Need to think of a way to add buttons to the KButtonPanel through the designer.

**Comment by Smurf-IV** [comment]
There are more issues, keep scrolling ?

**Comment by Wagnerp** [comment]
> There are more issues, keep scrolling ?

@Smurf-IV Are they on this thread?

**Comment by Wagnerp** [comment]
This is what I can see

image

?

**Comment by Smurf-IV** [comment]
> This is what I can see
> 

From the top:
image

Unresolved comments

**Comment by Wagnerp** [comment]
> 

Not appearing for me? :(

**Comment by Smurf-IV** [comment]
> Not appearing for me? :(

The url being used via the review is this:  https://github.com/Krypton-Suite/Standard-Toolkit/pull/773

**Comment by Wagnerp** [comment]
@Smurf-IV Going to close & restart

**Comment by Smurf-IV** [comment]
As this is being restarted, then should this be deleted ?

**Pull request closed without merging**
