### PR TITLE
- Restore usage of `typeof` for `[Editor(` designer statements

### PR DESCRIPTION
**Pull request by Smurf-IV**
- Make sure that VS 17.5.x can design ribbons in .net48 projects

#66

@Wagnerp Not sure what these mean..
Will try to solve, unless you accept.
image

Because building in release for the Ribbon examples passes:
image

### CODE REVIEW

**Comment by Wagnerp** [comment]
@Smurf-IV Might need to clean it before building it. I'm not able to test it before Friday.

**Comment by Smurf-IV** [comment]
> @Smurf-IV Might need to clean it before building it. I'm not able to test it before Friday.

It thought the option I chose was the "nightly build".
Just ran the step to delete, and then nightly again and got the this slightly different result:
image

**Comment by Wagnerp** [comment]
> > @Smurf-IV Might need to clean it before building it. I'm not able to test it before Friday.
> 
> It thought the option I chose was the "nightly build".
> Just ran the step to delete, and then nightly again and got the this slightly different result:
> image
> 

@Smurf-IV Try deleting the '* - Backup.csproj' files. It might be interrupting the build process.

**Comment by Smurf-IV** [comment]
> @Smurf-IV Try deleting the '* - Backup.csproj' files. It might be interrupting the build process.

They do not exist. :-(

**Comment by Wagnerp** [comment]
@Smurf-IV I think it thinks that `Backup.Navigator 2022` is a file extension

**Comment by Wagnerp** [comment]
@Smurf-IV  So just remove the ` - Backup` portion of the file name and it should work

**Comment by Smurf-IV** [comment]
> @Smurf-IV So just remove the ` - Backup` portion of the file name and it should work

Ok, this is weird.. Where did all the warnings go ?
image

**Comment by Wagnerp** [comment]
> > @Smurf-IV So just remove the ` - Backup` portion of the file name and it should work
> 
> Ok, this is weird.. Where did all the warnings go ?
> image
> 

The majority of the warnings were related to the ribbon project, so maybe the commit somehow cleared them out?

**Pull request merged**
