### PR TITLE
* `KryptonMessageBox` Images

### PR DESCRIPTION
**Pull request by Wagnerp**
* `KryptonMessageBox` using the `KryptonMessageBoxIcon.Shield` will now display the correct image for the version of the OS

image

### CODE REVIEW

**Comment by Wagnerp** [comment]
@Smurf-IV Is this ok to merge?

**Comment by Smurf-IV** [comment]
> @Smurf-IV Is this ok to merge?

No, it has outstanding comments, e.g.
image

**Comment by Wagnerp** [comment]
> > @Smurf-IV Is this ok to merge?
> 
> No, it has outstanding comments, e.g. image

Do you mean have a 5th button with a KCommand linked to it? Most of the new strings are now used in the extended toolkit, so they can be controlled from one central location.

**Comment by Smurf-IV** [comment]
> Do you mean have a 5th button with a KCommand linked to it? Most of the new strings are now used in the extended toolkit, so they can be controlled from one central location.

No.. If you look at the existing text in the buttons, then three of them are using "x" as the key accelerator.

**Comment by Wagnerp** [comment]
> > Do you mean have a 5th button with a KCommand linked to it? Most of the new strings are now used in the extended toolkit, so they can be controlled from one central location.
> 
> No.. If you look at the existing text in the buttons, then three of them are using "x" as the key accelerator.

Would you mind posting a screenshot?

**Comment by Smurf-IV** [comment]
image

**Comment by Wagnerp** [comment]
> image

Ah... now I understand, will fix today :)

**Comment by Wagnerp** [comment]
Updated log

image

**Pull request merged**
