### PR TITLE
* 1184 feature request a proper splashscreen item

### PR DESCRIPTION
**Pull request by PWagner1**
* Implement #1184 

image

### CODE REVIEW

**Comment by giduac** [comment]
@PWagner1 
I get several errors building this branch

image

@PWagner1, @Smurf-IV & @Ahmed-Abdelhameed 
Wondering, since this isn't a control, if it would be better to place this in Extended...?

**Comment by PWagner1** [comment]
> @PWagner1 I get several errors building this branch
> 
> image
> 
> @PWagner1, @Smurf-IV & @Ahmed-Abdelhameed Wondering, since this isn't a control, if it would be better to place this in Extended...?

@giduac 

No errors here, the plan is to create a `visx` package for common items.

image

**Comment by giduac** [comment]
@PWagner1 

Refreshed the branch...

The testform example for this is not functional (yet) .. ?

**Comment by PWagner1** [comment]
> @PWagner1
> 
> Refreshed the branch...
> 
> The testform example for this is not functional (yet) .. ?

@giduac 

Can you upload a image of the affected code?

**Comment by giduac** [comment]
@PWagner1 

The interface to setup the splash and then start it does nothing.
Give it a try...

**Comment by Smurf-IV** [comment]
All,
The splash screen is a component of the VB WinForms, So this is where the boundary for extended or not is blurred.

**Comment by PWagner1** [comment]
> All, The splash screen is a component of the VB WinForms, So this is where the boundary for extended or not is blurred.

I think we should take the same approach to it as both [KryptonAboutBox](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Toolkit/KryptonAboutBox.html) & [KryptonInputBox](https://krypton-suite.github.io/Standard-Toolkit-Online-Help/Source/Help/Output/articles/Toolkit/KryptonInputBox.html)

image

image

**Comment by Smurf-IV** [comment]
> @PWagner1
> 
> The interface to setup the splash and then start it does nothing. Give it a try...

This needs to be fixed !

**Comment by PWagner1** [comment]
> > @PWagner1
> > The interface to setup the splash and then start it does nothing. Give it a try...
> 
> This needs to be fixed !

@Smurf-IV & @giduac 

Coming up...

image

**Comment by PWagner1** [comment]
Splash

**Comment by PWagner1** [comment]
image

**Comment by PWagner1** [comment]
All good now :)

image

**Comment by PWagner1** [comment]
Now very customisable, give it a go

**Pull request merged**
