### PR TITLE
* 1715 bug 90247204 beta not implemented exception thrown for getribbonbackcolorstyle paletteoffice2010basecs v90

### LINKED ISSUE #1299: [Bug]: Not Implemented - Please Submit?
**Describe the bug**
After Update to the last `canary`-NuGet-Release the following message box will shown:

**To Reproduce**
RibbonTab with context selected programatically.

**Screenshots**
grafik
grafik

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Visual Studio 2019 Pro
 - Framework/.NET Version: 4.8.1
 - Toolkit Version: 90.24.1.22 (canary)

### PR DESCRIPTION
**Pull request by PWagner1**
* Resolved #1299 & #1715 

image

### CODE REVIEW

**Comment by giduac** [comment]
Testing on your branch

Is this error connected to the changes?

https://github.com/user-attachments/assets/be954cb9-8c53-4606-b152-9d40d49390e6

**Comment by PWagner1** [comment]
> Testing on your branch
> 
> Is this error connected to the changes?
> 
>  devenv_2htQNgNMU8.mp4

Hi @giduac 

No, as the changes doesn't touch that part of the code. Appears to be a new, separate bug?

**Comment by giduac** [comment]
> > Testing on your branch
> > Is this error connected to the changes?
> > devenv_2htQNgNMU8.mp4
> 
> Hi @giduac
> 
> No, as the changes doesn't touch that part of the code. Appears to be a new, separate bug?

I'm busy, can you test this on a fresh alpha branch if it's in there too.

**Comment by PWagner1** [comment]
> > > Testing on your branch
> > > Is this error connected to the changes?
> > > devenv_2htQNgNMU8.mp4
> > 
> > 
> > Hi @giduac
> > No, as the changes doesn't touch that part of the code. Appears to be a new, separate bug?
> 
> I'm busy, can you test this on a fresh alpha branch if it's in there too.

Will do

**Comment by PWagner1** [comment]
@giduac 

Update, yes I can confirm that it's a separate bug, not related to this PR.

**Comment by giduac** [comment]
> @giduac
> 
> Update, yes I can confirm that it's a separate bug, not related to this PR.

@PWagner1 
Not sure how this came into existence.
commit:  c7499ffb8dc416797696b8831c9473cdceb5d92e 
is OK and from (the next one)
commit: 8f94d5141ceacb6ddafd3e04d3ac22d1fa0ee172
the error is there.

Fastest way is way, imo, is to get the error sorted...

**Comment by PWagner1** [comment]
> > @giduac
> > Update, yes I can confirm that it's a separate bug, not related to this PR.
> 
> @PWagner1 Not sure how this came into existence. commit: [c7499ff](https://github.com/Krypton-Suite/Standard-Toolkit/commit/c7499ffb8dc416797696b8831c9473cdceb5d92e) is OK and from (the next one) commit: [8f94d51](https://github.com/Krypton-Suite/Standard-Toolkit/commit/8f94d5141ceacb6ddafd3e04d3ac22d1fa0ee172) the error is there.
> 
> Fastest way, imo, is to get the error sorted...

@giduac 

So https://github.com/Krypton-Suite/Standard-Toolkit/commit/c7499ffb8dc416797696b8831c9473cdceb5d92e is ok?

**Comment by giduac** [comment]
> > > @giduac
> > > Update, yes I can confirm that it's a separate bug, not related to this PR.
> > 
> > 
> > @PWagner1 Not sure how this came into existence. commit: [c7499ff](https://github.com/Krypton-Suite/Standard-Toolkit/commit/c7499ffb8dc416797696b8831c9473cdceb5d92e) is OK and from (the next one) commit: [8f94d51](https://github.com/Krypton-Suite/Standard-Toolkit/commit/8f94d5141ceacb6ddafd3e04d3ac22d1fa0ee172) the error is there.
> > Fastest way, imo, is to get the error sorted...
> 
> @giduac
> 
> So [c7499ff](https://github.com/Krypton-Suite/Standard-Toolkit/commit/c7499ffb8dc416797696b8831c9473cdceb5d92e) is ok?

yes and the next is flawed

**Comment by giduac** [comment]
The it must be this:

image

**Comment by PWagner1** [comment]
> The it must be this:
> 
> image

Was it removed or added to the code?

**Comment by PWagner1** [comment]
@giduac 

Right, I've introduced a temporary fix, but added a note 

```cs
   // ToDo: Find out why this is a problem... _ribbonColours[(int)SchemeOfficeColors.ButtonNavigatorChecked2],
```

**Comment by giduac** [comment]
> > The it must be this:
> > image
> 
> Was it removed or added to the code?

I turned that of and it's still there.


> @giduac
> 
> Right, I've introduced a temporary fix, but added a note
> 
> ```cs
>    // ToDo: Find out why this is a problem... _ribbonColours[(int)SchemeOfficeColors.ButtonNavigatorChecked2],
> ```

Fair enough. 
That can be sorted in a separate ticket.

All themes endure setting the contextname now:

https://github.com/user-attachments/assets/2cce7a05-0ae6-48b7-9783-01b75fd98791

**Review by giduac — APPROVED** [review]
Approved after a good old afternoon of troubleshooting ;)

**Pull request merged**
