### PR TITLE
Alpha removedotnet5

### PR DESCRIPTION
**Pull request by Wagnerp**
- Remove .NET 5 as per lifecycle (Feb 2022), planned build 6.2201

### CODE REVIEW

**Comment by Wagnerp** [comment]
Setting this to draaft

**Comment by Smurf-IV** [comment]
.Net 5 "May" be removed from 2022 solution but not the 2019.. 
There are still a lot of Nuget packages that do not support .net6 
AND a lot of Pluggins for VS that are not compatible with VS17 (i.e. Resharper !!)

**Comment by Wagnerp** [comment]
> .Net 5 "May" be removed from 2022 solution but not the 2019.. There are still a lot of Nuget packages that do not support .net6 AND a lot of Pluggins for VS that are not compatible with VS17 (i.e. Resharper !!)

Might be better to wait until EOL (May 2022)

**Comment by Wagnerp** [comment]
@Smurf-IV What if we reopen the idea of having `Lite` packages?

- `Lite` => net framework 4.8, .NET Core 3.1, .NET 6/7
- 'Other' => net framework 4.6.2 - 4.8, .NET Core 3.1, .NET 6/5/7

**Comment by Smurf-IV** [comment]
> @Smurf-IV What if we reopen the idea of having `Lite` packages?
> 
>     * `Lite` => net framework 4.8, .NET Core 3.1, .NET 6/7
> 

The "Lite" package should not include 7 in that case !
Not until it is actually released.

**Comment by Wagnerp** [comment]
> The "Lite" package should not include 7 in that case

The change would only affect the Stable/Signed releases, so 7 won't be included until November.

**Comment by Wagnerp** [comment]
Closing, due to previous comments

**Pull request closed without merging**
