### PR TITLE
* Forward recent fixes for KMbox for V90

### PR DESCRIPTION
**Pull request by Wagnerp**
* Forward recent fixes for KMbox for V90

image

### CODE REVIEW

**Review by giduac — CHANGES_REQUESTED** [review]
These forwarded fixes are incomplete although the changelog includes all three. Two fixes are missing. actually.

I suggest to let @Ahmed-Abdelhameed finish these fixes while it also is a good case for him getting started on the Toolkit.

**Comment by Wagnerp** [comment]
> These forwarded fixes are incomplete although the changelog includes all three. Two fixes are missing. actually. Also `VisualMessageBoxRtlAwareForm.cs` is missing form this.
> 
> I suggest to let @Ahmed-Abdelhameed finish these fixes while it also is a good case for him getting started on the Toolkit. This already was set in motion: [#1599 (comment)](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1599#issuecomment-2214913516)
> 
> Thanks for the consideration.

Hi @giduac 

I couldn't find the line `this._panelContentArea.Margin = new System.Windows.Forms.Padding(4);` in V90. Seems that there are some changes between V85 and V90.

**Comment by giduac** [comment]
> > These forwarded fixes are incomplete although the changelog includes all three. Two fixes are missing. actually. Also `VisualMessageBoxRtlAwareForm.cs` is missing form this.
> > I suggest to let @Ahmed-Abdelhameed finish these fixes while it also is a good case for him getting started on the Toolkit. This already was set in motion: [#1599 (comment)](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1599#issuecomment-2214913516)
> > Thanks for the consideration.
> 
> Hi @giduac
> 
> I couldn't find the line `this._panelContentArea.Margin = new System.Windows.Forms.Padding(4);` in V90. Seems that there are some changes between V85 and V90.

Hi @Wagnerp,

I would be a good start for @Ahmed-Abdelhameed and let him also finish the changes all together for V90.

**Comment by Wagnerp** [comment]
> > > These forwarded fixes are incomplete although the changelog includes all three. Two fixes are missing. actually. Also `VisualMessageBoxRtlAwareForm.cs` is missing form this.
> > > I suggest to let @Ahmed-Abdelhameed finish these fixes while it also is a good case for him getting started on the Toolkit. This already was set in motion: [#1599 (comment)](https://github.com/Krypton-Suite/Standard-Toolkit/issues/1599#issuecomment-2214913516)
> > > Thanks for the consideration.
> > 
> > 
> > Hi @giduac
> > I couldn't find the line `this._panelContentArea.Margin = new System.Windows.Forms.Padding(4);` in V90. Seems that there are some changes between V85 and V90.
> 
> Hi @Wagnerp,
> 
> I would be a good start for @Ahmed-Abdelhameed and let him also finish the changes all together for V90.

Hi @giduac 

I've done fixes for 2 of them. There are a number of API changes between v85 & v90, but see  my comment re: https://github.com/Krypton-Suite/Standard-Toolkit/issues/1613#issuecomment-2223558869

**Pull request merged**
